### PR TITLE
Remove GTK dependency for use on headless nodes

### PR DESCRIPTION
**Pull request by michaelhallquist**
Hi Chris,

Thanks for the great package! One challenge we've faced is that the package imports RGtk2 and cairoDevice even though these are only used, to my knowledge, for the GUI. We are using the package in a cluster environment mostly for computation, not visualization. I removed the dependency and load the packages when the GUI is requested. This seems to keep things functioning, but allow most of the package to work without GTK etc.

Best,
Michael

### CODE REVIEW

**Comment by cwatson** [comment]
Hi @michaelhallquist this looks great; I have been meaning to do something like this to solve the GTK issues.
I will test it and merge it soon. If you would like to discuss attribution for this contribution, please email me personally.

**Comment by michaelhallquist** [comment]
Hi Chris,

Great, I'm glad this is helpful! No need for formal attribution -- it was a small change. Thanks again for developing the package.

Michael

**Comment by cwatson** [comment]
@michaelhallquist could you make sure I have push access to your fork? See [this help page](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) for necessary steps. There are some changes I will need to make. Thanks!

**Comment by michaelhallquist** [comment]
Hi Chris,

The "Allow edits from maintainers" checkbox already appears to be active. Are you getting a permission error when you try to commit?

Thanks,
Michael

**Comment by cwatson** [comment]
No, I just wanted to make sure before I made an attempt. Thanks!

**Comment by cwatson** [comment]
Hi @michaelhallquist I accidentally pushed an update to the @PennStateDEPENdLab `master` branch. You can reject it if you want, and fork the `master` branch from here. Thanks again for your contribution!

**Pull request merged**
